name: Go
on: [push, pull_request]
jobs:
  deploy:
    if: github.event_name != 'pull_request' && startsWith(github.ref, 'refs/tags/')
    runs-on: ubuntu-latest
    steps:
    - uses: actions/setup-go@v1
      with:
        go-version: 1.16
    - uses: actions/checkout@v1

    - name: stable release
      uses: goreleaser/goreleaser-action@v2
      with:
        version: latest
        args: --config goreleaser-stable.yml
      env:
        GITHUB_TOKEN: ${{ secrets.CUSTOM_GITHUB_TOKEN }}
    - name: shell tests
      run: |
        echo "Running"
        ls -al dist


